{
 "title": "iotex",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "hostip", "query": "172.17.0.1" }
  ]
 },
 "panels": [
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "iotex_dispatch_request",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "iotex_dispatch_request{instance=\"$hostip:8080\",job=\"iotex-testnet\",method=\"AddAction\",succeed=\"false\"}"
    }
   ]
  },
  {
   "title": "iotex_action_pool_perf",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "iotex_action_pool_perf{instance=\"$hostip:8080\",job=\"iotex-testnet\",type=\"reset\"}"
    }
   ]
  },
  {
   "title": "iotex_statefactory_perf",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "iotex_statefactory_perf{chainID=\"1\",instance=\"$hostip:8080\",job=\"iotex-testnet\",topic=\"Commit\"}"
    }
   ]
  },
  {
   "title": "iotex_state_db",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "iotex_state_db{instance=\"$hostip:8080\",job=\"iotex-testnet\",type=\"get\"}\r\n"
    },
    {
     "expr": "iotex_state_db{instance=\"$hostip:8080\",job=\"iotex-testnet\",type=\"put\"}"
    }
   ]
  },
  {
   "title": "iotex_db_batch_size",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "iotex_db_batch_size{instance=\"$hostip:8080\",job=\"iotex-testnet\"}\n"
    }
   ]
  },
  {
   "title": "iotex_consensus",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "iotex_consensus{instance=\"$hostip:8080\",job=\"iotex-testnet\",result=\"E_CALIBRATE\"}\r\n"
    },
    {
     "expr": "iotex_consensus{instance=\"$hostip:8080\",job=\"iotex-testnet\",result=\"E_PREPARE\"}"
    }
   ]
  },
  {
   "title": "iotex_heartbeat_status",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "iotex_heartbeat_status{instance=\"$hostip:8080\",job=\"iotex-testnet\",source=\"1\",status_type=\"actpoolCapacity\"}\r\n"
    },
    {
     "expr": "iotex_heartbeat_status{instance=\"$hostip:8080\",job=\"iotex-testnet\",source=\"1\",status_type=\"actpoolSize\"}\r\n"
    },
    {
     "expr": "iotex_heartbeat_status{instance=\"$hostip:8080\",job=\"iotex-testnet\",source=\"1\",status_type=\"blockchainHeight\"}\r\n"
    },
    {
     "expr": "iotex_heartbeat_status{instance=\"$hostip:8080\",job=\"iotex-testnet\",source=\"1\",status_type=\"pendingRolldposEvents\"}\r\n"
    },
    {
     "expr": "iotex_heartbeat_status{instance=\"$hostip:8080\",job=\"iotex-testnet\",source=\"1\",status_type=\"targetHeight\"}\r\n"
    },
    {
     "expr": "iotex_heartbeat_status{instance=\"$hostip:8080\",job=\"iotex-testnet\",source=\"node\",status_type=\"numPeers\"}\r\n"
    },
    {
     "expr": "iotex_heartbeat_status{instance=\"$hostip:8080\",job=\"iotex-testnet\",source=\"node\",status_type=\"pendingDispatcherEvents\"}"
    }
   ]
  },
  {
   "title": "iotex_blockchain_perf",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "iotex_blockchain_perf{chainID=\"1\",instance=\"$hostip:8080\",job=\"iotex-testnet\",topic=\"CommitBlock\"}\r\n"
    },
    {
     "expr": "iotex_blockchain_perf{chainID=\"1\",instance=\"$hostip:8080\",job=\"iotex-testnet\",topic=\"ValidateBlock\"}\r\n"
    },
    {
     "expr": "iotex_blockchain_perf{chainID=\"1\",instance=\"$hostip:8080\",job=\"iotex-testnet\",topic=\"putBlock\"}\r\n"
    },
    {
     "expr": "iotex_blockchain_perf{chainID=\"1\",instance=\"$hostip:8080\",job=\"iotex-testnet\",topic=\"putReceipt\"}\r\n"
    },
    {
     "expr": "iotex_blockchain_perf{chainID=\"1\",instance=\"$hostip:8080\",job=\"iotex-testnet\",topic=\"runActions\"}\r\n"
    },
    {
     "expr": "iotex_blockchain_perf{chainID=\"1\",instance=\"$hostip:8080\",job=\"iotex-testnet\",topic=\"sf.Commit\"}\r\n"
    },
    {
     "expr": "iotex_blockchain_perf{chainID=\"1\",instance=\"$hostip:8080\",job=\"iotex-testnet\",topic=\"validate\"}"
    }
   ]
  }
 ]
}